apiVersion: v2
name: dhcpd-dns-pxe
description: DHCP server with dnsmasq
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://source.isc.org/git/dhcp.git
- http://thekelleys.org.uk/gitweb/?p=dnsmasq.git
type: application
version: 0.1.5
appVersion: "4.4.3-r0-2.86-r2"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
