---
# There is a problem with kubelet volume mounting
#  See https://github.com/kubernetes/kubernetes/pull/71663
#  Workaround here requires manually copying data into mounted
#  path after installation completes
- name: TODO remove when bug 1294 is fixed - unmount kubelet vol
  mount:
    fstype: ext4
    path: /var/lib/kubelet
    src: /dev/mapper/luks-kubelet
    state: unmounted

- name: Reset Kubernetes component
  command: kubeadm reset --force
  register: reset_cluster

- name: Set kubeadm configuration
  copy:
    dest: /etc/kubernetes/kubeadm-config.yaml
    content: |
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      bootstrapTokens:
      - token: {{ vault_k8s.join_token }}
        ttl: 1h0m0s
        usages:
        - signing
        - authentication
        groups:
        - system:bootstrappers:kubeadm:default-node-token
      localAPIEndpoint:
        advertiseAddress: {{ k8s.master_ip }}
        bindPort: 6443
      nodeRegistration:
        criSocket: unix:///var/run/cri-dockerd.sock
        imagePullPolicy: IfNotPresent
        name: {{ ansible_fqdn }}
        taints:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      # certSans deprecated in 1.24
      # apiServer:
      #   certSans:
      #   - {{ k8s.master_ip }}
      certificatesDir: /etc/kubernetes/pki
      controllerManager:
        extraArgs:
          address: 0.0.0.0
      dns: {}
      etcd:
        local:
          dataDir: /var/lib/etcd
      imageRepository: k8s.gcr.io
      kubernetesVersion: v{{ k8s.version }}
      networking:
        podSubnet: {{ k8s.pod_network }}
        serviceSubnet: {{ k8s.service_network }}
      scheduler:
        extraArgs:
          address: 0.0.0.0

- name: Init Kubernetes cluster
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  register: init_cluster
  when: reset_cluster is succeeded
